Diagnostica
===========

La seconda parte del progetto riguarda diagnosticare particolari richieste
fatte dall'utente, diagnostiche che verranno svolte su circuiti noti e già
processati nella parte di simulazione.
