Introduzione
============

In questa documentazione verrà presentato il progetto relativo al corso di
Algoritmi e Strutture Dati, materia facente parte della laurea magistrale in
ingegneria informatica, tenuto dalla Professoressa Marina Zanella.

Verranno di seguito illustrati la tipologia di problema e, in modo più
approfondito, le metodologie risolutive utilizzate, trattando sia le strutture
dati per la gestione delle informazioni relative al problema sia gli algoritmi.
Al termine del documento verranno discussi i risultati ottenuti e tutti gli
accorgimenti presi durante lo sviluppo per ridurre i tempi di esecuzione e per
ottimizzare le prestazioni per risolvere il problema.

Il software è stato realizzato con il supporto della piattaforma web *GitHub*,
strumento molto utile per la gestione del progetto durante la sua creazione e
sviluppo; di conseguenza tutto il materiale può essere reperito nella repository
 <!--\href{https://github.com/BoreaWolf/Circuits}{Circuits}-->.

TODO: Struttura zip

TODO: Compilazione

<!--
%	Progetto per ASD
%	Tutto presente su GitHub @
%	Struttura dello zip che verrà inviato
%	Come compilare
-->

