LaTeX Input:					template/mmd-thesis-header
Title:							Circuits
Author:							Riccardo Orizio
Languages:      				italian
LaTeX Mode:						memoir
Base Header Level:				2
ToC Depth:						2
Document Title:					Progetto di Algoritmi e Strutture Dati
Formatted Title:				Simulazione e Diagnostica di Circuiti Digitali
Registration Number:			91956
Supervisor:						Prof.ssa Marina Zanella
University:						Università degli Studi di Brescia
Faculty:						Dipartimento di Ingegneria dell'Informazione
Course:							Corso di Laurea Magistrale in Ingegneria
								Informatica
Academic Year:					201x-201x
LaTeX Input:					template/mmd-natbib-plain
LaTeX Input:					template/mmd-equation-mode
LaTeX Input:					template/mmd-thesis-begin-doc
LaTeX Input:					template/mmd-thesis-titlepage
LaTeX Input:					template/mmd-thesis-index
LaTeX Footer:					template/mmd-thesis-footer

<!-- % The empty line is important *in every file* -->
